apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-xhlf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-xhlf
    app.kubernetes.io/part-of: test-app-voft
  name: test-component-xhlf
  namespace: build-e2e-sjcl-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-xhlf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-xhlf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:401637cf687379431e49550f6f39adc8cab57562da9538cc2a2750199afa4ed5
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
